'use client';

import { useState } from 'react';
import { Download, FileText, FileSpreadsheet, Code, Copy, Check } from 'lucide-react';
import { toast } from 'sonner';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

interface ExportAuditMenuProps {
  auditData: any;
  targetRef: React.RefObject<HTMLDivElement | null>;
}

export function ExportAuditMenu({ auditData, targetRef }: ExportAuditMenuProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const [showIframeModal, setShowIframeModal] = useState(false);
  const [copied, setCopied] = useState(false);
  const [htmlContent, setHtmlContent] = useState('');

  const handleExportPDF = async () => {
    if (!targetRef.current) return;
    setIsOpen(false);
    setIsExporting(true);
    toast.info('Generating PDF...');
    
    try {
      const canvas = await html2canvas(targetRef.current, { scale: 2 } as any);
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'px',
        format: [canvas.width, canvas.height]
      });
      pdf.addImage(imgData, 'PNG', 0, 0, canvas.width, canvas.height);
      pdf.save('gestions-seo-audit.pdf');
      toast.success('PDF downloaded successfully');
    } catch (e) {
      toast.error('Failed to generate PDF');
    }
    setIsExporting(false);
  };

  const handleExportCSV = () => {
    setIsOpen(false);
    
    let csvContent = "data:text/csv;charset=utf-8,";
    csvContent += "Type,Title,Group,Pages Affected\\n";
    auditData?.issues?.forEach((issue: any) => {
      // Escape commas in titles
      const title = `"${issue.title.replace(/"/g, '""')}"`;
      csvContent += `${issue.type},${title},${issue.group},${issue.count}\n`;
    });

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", "gestions-audit-issues.csv");
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    toast.success('CSV downloaded successfully');
  };

  const generateHTML = () => {
    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SEO Audit Report</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background: transparent; }
    </style>
</head>
<body class="p-4 sm:p-8">
    <div class="max-w-4xl mx-auto bg-white rounded-2xl shadow-sm border border-neutral-200 overflow-hidden">
        <div class="p-6 border-b border-neutral-100 bg-neutral-50/50 flex justify-between items-center">
            <div>
              <h2 class="text-xl font-medium text-neutral-900">SEO Audit Report</h2>
              <p class="text-sm text-neutral-500 mt-1">Generated by Gestions</p>
            </div>
            <div class="text-center">
              <span class="text-xs font-medium text-neutral-500 uppercase tracking-wider block mb-1">Health Score</span>
              <span class="text-4xl font-light text-neutral-900">${auditData.score}</span><span class="text-sm text-neutral-400">/100</span>
            </div>
        </div>
        
        <div class="p-6 border-b border-neutral-100 grid grid-cols-3 gap-4">
            <div class="bg-neutral-50 rounded-xl p-4 border border-neutral-100 text-center">
                <p class="text-xs font-medium text-neutral-900 uppercase tracking-wider mb-2">Errors</p>
                <p class="text-3xl font-light text-neutral-900">${auditData.errors}</p>
            </div>
            <div class="bg-neutral-50 rounded-xl p-4 border border-neutral-100 text-center">
                <p class="text-xs font-medium text-neutral-500 uppercase tracking-wider mb-2">Warnings</p>
                <p class="text-3xl font-light text-neutral-700">${auditData.warnings}</p>
            </div>
            <div class="bg-neutral-50 rounded-xl p-4 border border-neutral-100 text-center">
                <p class="text-xs font-medium text-neutral-400 uppercase tracking-wider mb-2">Notices</p>
                <p class="text-3xl font-light text-neutral-500">${auditData.notices}</p>
            </div>
        </div>

        <div class="p-6">
            <h3 class="text-sm font-medium text-neutral-900 mb-4">Issues Found</h3>
            <div class="flex flex-col gap-3">
                ${auditData.issues?.map((issue: any) => `
                <div class="flex items-center justify-between p-4 border border-neutral-100 rounded-xl bg-neutral-50/50">
                  <div>
                    <span class="inline-block px-2 py-1 text-[10px] font-medium rounded-full mb-1 ${issue.type==='Error'?'bg-neutral-900 text-white':issue.type==='Warning'?'bg-neutral-200 text-neutral-800':'bg-neutral-100 text-neutral-500'}">${issue.type}</span>
                    <h4 class="text-sm font-medium text-neutral-900">${issue.title}</h4>
                    <p class="text-xs text-neutral-500 mt-1">${issue.group}</p>
                  </div>
                  <div class="text-right">
                    <span class="text-lg font-light text-neutral-900">${issue.count}</span>
                    <span class="text-[10px] text-neutral-400 block">Pages</span>
                  </div>
                </div>
                `).join('')}
            </div>
        </div>
    </div>
</body>
</html>`;
  };

  const handleExportHTML = () => {
    setIsOpen(false);
    const html = generateHTML();
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = "gestions-audit-report.html";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success('HTML Report downloaded');
  };

  const handleShowIframe = () => {
    setIsOpen(false);
    const html = generateHTML();
    setHtmlContent(html);
    setShowIframeModal(true);
  };

  const copyIframe = () => {
    const encoded = btoa(unescape(encodeURIComponent(htmlContent)));
    const snippet = `<iframe src="data:text/html;base64,${encoded}" width="100%" height="800" style="border:none; border-radius: 12px; overflow:hidden;" title="SEO Audit Report"></iframe>`;
    navigator.clipboard.writeText(snippet);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="relative">
      <button 
        onClick={() => setIsOpen(!isOpen)}
        disabled={isExporting}
        className="flex items-center gap-2 px-4 py-2 bg-white border border-neutral-200 rounded-full text-xs font-medium text-neutral-700 hover:bg-neutral-50 transition-colors shadow-sm"
      >
        <Download className="w-4 h-4" /> Export Audit
      </button>

      {isOpen && (
        <div className="absolute right-0 mt-2 w-56 bg-white border border-neutral-200 rounded-xl shadow-lg overflow-hidden z-50">
          <div className="py-1">
            <button onClick={handleExportPDF} className="w-full text-left px-4 py-3 text-xs text-neutral-700 hover:bg-neutral-50 flex items-center gap-3">
              <FileText className="w-4 h-4 text-neutral-400" /> Export as PDF
            </button>
            <button onClick={handleExportCSV} className="w-full text-left px-4 py-3 text-xs text-neutral-700 hover:bg-neutral-50 flex items-center gap-3">
              <FileSpreadsheet className="w-4 h-4 text-green-500" /> Export Issues (CSV)
            </button>
            <div className="h-px bg-neutral-100 my-1"></div>
            <button onClick={handleExportHTML} className="w-full text-left px-4 py-3 text-xs text-neutral-700 hover:bg-neutral-50 flex items-center gap-3">
              <Code className="w-4 h-4 text-blue-500" /> Download HTML Report
            </button>
            <button onClick={handleShowIframe} className="w-full text-left px-4 py-3 text-xs text-neutral-700 hover:bg-neutral-50 flex items-center gap-3">
              <Copy className="w-4 h-4 text-purple-500" /> Get Embed Iframe
            </button>
          </div>
        </div>
      )}

      {showIframeModal && (
        <div className="fixed inset-0 bg-neutral-900/40 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl w-full max-w-2xl overflow-hidden shadow-2xl flex flex-col">
            <div className="p-6 border-b border-neutral-100 flex justify-between items-center">
              <div>
                <h3 className="font-medium text-neutral-900">Embed Audit Report</h3>
                <p className="text-xs text-neutral-500 mt-1">Copy this snippet to embed the current snapshot of your audit anywhere.</p>
              </div>
              <button onClick={() => setShowIframeModal(false)} className="text-neutral-400 hover:text-neutral-900">✕</button>
            </div>
            <div className="p-6 bg-neutral-50/50">
              <pre className="text-xs font-mono text-neutral-600 bg-neutral-100 p-4 rounded-xl overflow-x-auto whitespace-pre-wrap border border-neutral-200">
                &lt;iframe src="data:text/html;base64,...(encoded content)..." width="100%" height="800" style="border:none;"&gt;&lt;/iframe&gt;
              </pre>
            </div>
            <div className="p-6 border-t border-neutral-100 flex justify-end gap-3 bg-white">
              <button onClick={() => setShowIframeModal(false)} className="px-4 py-2 rounded-full text-xs font-medium text-neutral-600 hover:bg-neutral-50 transition-colors">
                Cancel
              </button>
              <button onClick={copyIframe} className="px-6 py-2 rounded-full text-xs font-medium bg-neutral-900 text-white hover:bg-black transition-colors flex items-center gap-2">
                {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                {copied ? 'Copied!' : 'Copy Iframe Code'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
